language: java
sudo: required
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "tookaa2" -p "$DOCKER_PASSWORD"
- chmod +x mvnw
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/app.jar -t tookaa2/se234-project-backend  .
- docker push tookaa2/se234-project-backend
- docker pull dto80/project234-frontend:latest
cache:
  directories:
  - "$HOME/.m2"